import socket
HOST = '192.168.15.46' 
PORT = 12345
socketCliente = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
enderecoServidor = (HOST, PORT)
socketCliente.connect(enderecoServidor)
#print('Digite X para sair')
#mensagem = input('Digite seu mensagem : ').encode()
print('BEM VINDO')
print('DIGITE ')
escolha = input('1 - Jogar\n0 - Sair\n').encode()
while escolha.decode() != '0' : #ou b'X'
    print('Brasil ganhou a copa de 2002? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2004? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2008? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2004? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2012? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2014? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
    print('Brasil ganhou a copa de 2018? ')
    resposta1 = input('1 - Sim\n0 - Não\n').encode()
    socketCliente.send(resposta1)
    mensagemRecebida = socketCliente.recv(100)
    print('Mensagem Recebida = ', mensagemRecebida.decode())
socketCliente.close()